name: Connect to AWS
on:
#  push:
  workflow_call:

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
permissions:
      id-token: write
      contents: read

jobs:
  AWS-Connect:
    runs-on: ubuntu-22.04
    container:
      image: node:18
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - ${{ github.workspace }}:/work
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_GITHUB_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name:  Show environment
        run: env
      - name:  Check AWS connectifity
        run: |
          pwd
          ls -l /work
          aws sts get-caller-identity
