name: Deploy
on:
  push:
  workflow_call:

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  STATE_S3BUCKET: ${{ vars.STATE_S3BUCKET }}

permissions:
      id-token: write
      contents: read

jobs:
  Deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_GITHUB_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name:  Show environment
        run: env

      - name:  Check AWS connectifity
        run: |
          aws sts get-caller-identity

      - name:  Run AWS deployment
        run: |
          make install

